package model.bean;
// Generated Mar 29, 2017 7:51:05 AM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "smndbwms")
public class Customer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Address address;
	private Person person;
	private String name;
	private Boolean isCompany;
	private int mobileNum;
	private int landNum;
	private String email;
	private List<Sales> saleses = new ArrayList<Sales>();

	public Customer() {
	}

	public Customer(Address address, Person person, String name, Boolean isCompany, int mobileNum, int landNum,
			String email, List<Sales> saleses) {
		this.address = address;
		this.person = person;
		this.name = name;
		this.isCompany = isCompany;
		this.mobileNum = mobileNum;
		this.landNum = landNum;
		this.email = email;
		this.saleses = saleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id")
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_person_id")
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_company")
	public Boolean getIsCompany() {
		return this.isCompany;
	}

	public void setIsCompany(Boolean isCompany) {
		this.isCompany = isCompany;
	}

	@Column(name = "mobile_num")
	public int getMobileNum() {
		return this.mobileNum;
	}

	public void setMobileNum(int mobileNum) {
		this.mobileNum = mobileNum;
	}

	@Column(name = "land_num")
	public int getLandNum() {
		return this.landNum;
	}

	public void setLandNum(int landNum) {
		this.landNum = landNum;
	}

	@Column(name = "email", length = 150)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public List<Sales> getSaleses() {
		return this.saleses;
	}

	public void setSaleses(List<Sales> saleses) {
		this.saleses = saleses;
	}

	@Override
	public String toString() {
		return "Customer [id=" + id + ", " + (address != null ? "address=" + address + ", " : "")
				+ (person != null ? "person=" + person + ", " : "") + (name != null ? "name=" + name + ", " : "")
				+ (isCompany != null ? "isCompany=" + isCompany + ", " : "") + "mobileNum=" + mobileNum + ", landNum="
				+ landNum + ", " + (email != null ? "email=" + email + ", " : "")
				+ (saleses != null ? "saleses=" + saleses : "") + "]";
	}
	

}
