package model.bean;
// Generated Mar 29, 2017 7:51:05 AM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InventoryCheck generated by hbm2java
 */
@Entity
@Table(name = "inventory_check", catalog = "smndbwms")
public class InventoryCheck implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Item item;
	private Person person;
	private Date date;
	private float lastQty;
	private float currentQty;
	private float actualQty;
	private float diffQty;

	public InventoryCheck() {
	}

	public InventoryCheck(Item item, Person person, Date date, float lastQty, float currentQty, float actualQty,
			float diffQty) {
		this.item = item;
		this.person = person;
		this.date = date;
		this.lastQty = lastQty;
		this.currentQty = currentQty;
		this.actualQty = actualQty;
		this.diffQty = diffQty;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "checker_id")
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "last_qty", precision = 12, scale = 0)
	public float getLastQty() {
		return this.lastQty;
	}

	public void setLastQty(float lastQty) {
		this.lastQty = lastQty;
	}

	@Column(name = "current_qty", precision = 12, scale = 0)
	public float getCurrentQty() {
		return this.currentQty;
	}

	public void setCurrentQty(float currentQty) {
		this.currentQty = currentQty;
	}

	@Column(name = "actual_qty", precision = 12, scale = 0)
	public float getActualQty() {
		return this.actualQty;
	}

	public void setActualQty(float actualQty) {
		this.actualQty = actualQty;
	}

	@Column(name = "diff_qty", precision = 12, scale = 0)
	public float getDiffQty() {
		return this.diffQty;
	}

	public void setDiffQty(float diffQty) {
		this.diffQty = diffQty;
	}

	@Override
	public String toString() {
		return "InventoryCheck [id=" + id + ", " + (item != null ? "item=" + item + ", " : "")
				+ (person != null ? "person=" + person + ", " : "") + (date != null ? "date=" + date + ", " : "")
				+ "lastQty=" + lastQty + ", currentQty=" + currentQty + ", actualQty=" + actualQty + ", diffQty="
				+ diffQty + "]";
	}
	

}
