package model.bean;
// Generated Mar 30, 2017 11:46:21 AM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchasingItem generated by hbm2java
 */
@Entity
@Table(name = "purchasing_item", catalog = "smndbwms")
public class PurchasingItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Item item;
	private Purchase purchase;
	private Date date;
	private float costPrice;
	private float qty;
	private String refrence;

	public PurchasingItem() {
	}

	public PurchasingItem(Item item, Purchase purchase, Date date, float costPrice, float qty, String refrence) {
		this.item = item;
		this.purchase = purchase;
		this.date = date;
		this.costPrice = costPrice;
		this.qty = qty;
		this.refrence = refrence;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "purchase_id")
	public Purchase getPurchase() {
		return this.purchase;
	}

	public void setPurchase(Purchase purchase) {
		this.purchase = purchase;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "cost_price", precision = 12, scale = 0)
	public float getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(float costPrice) {
		this.costPrice = costPrice;
	}

	@Column(name = "qty", precision = 12, scale = 0)
	public float getQty() {
		return this.qty;
	}

	public void setQty(float qty) {
		this.qty = qty;
	}

	@Column(name = "refrence", length = 45)
	public String getRefrence() {
		return this.refrence;
	}

	public void setRefrence(String refrence) {
		this.refrence = refrence;
	}

	@Override
	public String toString() {
		return "PurchasingItem [id=" + id + ", " + (item != null ? "item=" + item + ", " : "")
				+ (purchase != null ? "purchase=" + purchase + ", " : "") + (date != null ? "date=" + date + ", " : "")
				+ "costPrice=" + costPrice + ", qty=" + qty + ", " + (refrence != null ? "refrence=" + refrence : "")
				+ "]";
	}
	

}
