package model.bean;
// Generated Mar 30, 2017 11:46:21 AM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Purchase generated by hbm2java
 */
@Entity
@Table(name = "purchase", catalog = "smndbwms")
public class Purchase implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Person person;
	private Supplier supplier;
	private Date date;
	private float totalCost;
	private String refrence;
	private List<PurchasingItem> purchasingItems = new ArrayList<PurchasingItem>();

	public Purchase() {
	}

	public Purchase(Person person, Supplier supplier, Date date, float totalCost, String refrence,
			List<PurchasingItem> purchasingItems) {
		this.person = person;
		this.supplier = supplier;
		this.date = date;
		this.totalCost = totalCost;
		this.refrence = refrence;
		this.purchasingItems = purchasingItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "purchaser_id")
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "supplier_id")
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "total_cost", precision = 12, scale = 0)
	public float getTotalCost() {
		return this.totalCost;
	}

	public void setTotalCost(float totalCost) {
		this.totalCost = totalCost;
	}

	@Column(name = "refrence", length = 45)
	public String getRefrence() {
		return this.refrence;
	}

	public void setRefrence(String refrence) {
		this.refrence = refrence;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "purchase")
	public List<PurchasingItem> getPurchasingItems() {
		return this.purchasingItems;
	}

	public void setPurchasingItems(List<PurchasingItem> purchasingItems) {
		this.purchasingItems = purchasingItems;
	}

	@Override
	public String toString() {
		return "Purchase [id=" + id + ", " + (person != null ? "person=" + person + ", " : "")
				+ (supplier != null ? "supplier=" + supplier + ", " : "") + (date != null ? "date=" + date + ", " : "")
				+ "totalCost=" + totalCost + ", " + (refrence != null ? "refrence=" + refrence + ", " : "")
				+ (purchasingItems != null ? "purchasingItems=" + purchasingItems : "") + "]";
	}
	

}
