package model.bean;
// Generated Mar 30, 2017 11:46:21 AM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sales generated by hbm2java
 */
@Entity
@Table(name = "sales", catalog = "smndbwms")
public class Sales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Customer customer;
	private Person person;
	private Date date;
	private float totalPrice;
	private String refrence;
	private List<SalesItem> salesItems = new ArrayList<SalesItem>();

	public Sales() {
	}

	public Sales(Customer customer, Person person, Date date, float totalPrice, String refrence, List<SalesItem> salesItems) {
		this.customer = customer;
		this.person = person;
		this.date = date;
		this.totalPrice = totalPrice;
		this.refrence = refrence;
		this.salesItems = salesItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sales_by")
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "total_price", precision = 12, scale = 0)
	public float getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(float totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "refrence", length = 45)
	public String getRefrence() {
		return this.refrence;
	}

	public void setRefrence(String refrence) {
		this.refrence = refrence;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sales")
	public List<SalesItem> getSalesItems() {
		return this.salesItems;
	}

	public void setSalesItems(List<SalesItem> salesItems) {
		this.salesItems = salesItems;
	}

	@Override
	public String toString() {
		return "Sales [id=" + id + ", " + (customer != null ? "customer=" + customer + ", " : "")
				+ (person != null ? "person=" + person + ", " : "") + (date != null ? "date=" + date + ", " : "")
				+ "totalPrice=" + totalPrice + ", " + (refrence != null ? "refrence=" + refrence + ", " : "")
				+ (salesItems != null ? "salesItems=" + salesItems : "") + "]";
	}
	

}
