package model.bean;
// Generated Mar 29, 2017 7:51:05 AM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StockMoveType generated by hbm2java
 */
@Entity
@Table(name = "stock_move_type", catalog = "smndbwms")
public class StockMoveType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private List<StockMove> stockMoves = new ArrayList<StockMove>();

	public StockMoveType() {
	}

	public StockMoveType(String name, List<StockMove> stockMoves) {
		this.name = name;
		this.stockMoves = stockMoves;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 70)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockMoveType")
	public List<StockMove> getStockMoves() {
		return this.stockMoves;
	}

	public void setStockMoves(List<StockMove> stockMoves) {
		this.stockMoves = stockMoves;
	}

	@Override
	public String toString() {
		return "StockMoveType [id=" + id + ", " + (name != null ? "name=" + name + ", " : "")
				+ (stockMoves != null ? "stockMoves=" + stockMoves : "") + "]";
	}
	

}
